#!/usr/bin/env ruby

require_relative './lib/work_timer'

if ARGV.length > 1 || ARGV.first == ''
  warn "usage: timer [LOG_FILE]"
  exit 2
end

session = if ARGV.empty?
  WorkTimer::Session.new
else
  WorkTimer::RecordedSession.new(ARGV.fetch(0))
end

begin
  session.run
rescue WorkTimer::CorruptLogError, WorkTimer::LogAccessError => error
  warn "timer: #{error.message}"
  exit 1
end
