#!/usr/bin/env ruby

#
# AtCoder Beginner Contestセットアップ
#
# *.pyというファイルを*-0.pyに変える
# a.py, b.py, c.py, d.pyを作る



Dir.glob("*").map{ |fname| File.rename(fname, fname.gsub(".py", "-0.py")) }
['a', 'b', 'c', 'd'].each do |fname|
  `touch #{fname}.py`
end
