#!/bin/bash

GOMI_PATH="$HOME"/gomi

# USAGE
usage_exit() {
  echo "usage: gomi [-l | -h] target ..." 1>&2
  echo "options:"
  echo "  -l  Show $GOMI_PATH/*"
  echo "  -h  Show this help"
  exit 1
}

check_opts() {
  help_flag=false
  ls_flag=false
  while getopts lh OPT
  do
    case $OPT in
      "h") help_flag=true
      ;;
      "l") ls_flag=true
      ;;
      \? ) usage_exit
      ;;
    esac
  done

  shift $((OPTIND - 1))

  if $ls_flag; then
    ls_file
  elif $help_flag; then
    usage_exit
  else
    main "$@"
  fi
}

move_file() {
  # ファイル存在確認
  if [[ ! -e "$1" ]]; then
    echo "gomi: $1: No such file or directory"
    exit 1
  fi

  if [[ ! -e "$GOMI_PATH" ]]; then # "$GOMI_PATH"が存在しなければ作成
    \mkdir "$GOMI_PATH"
  fi

   # ファイルを移動するディレクトリ作成
  dirname=$(date '+%Y%m%d')
  \mkdir -p "$GOMI_PATH"/"$dirname"

  # ファイルを"$GOMI_PATH"/$dirnameに移動
  if [[ -e "$GOMI_PATH"/"$dirname"/"$1" ]]; then # 同名のファイルが存在した場合、filename.1に名称変更
    cnt=1
    fname="$1.$cnt"
    # filename.1が存在する場合、かぶりのない番号をつける
    while [[ -e "$GOMI_PATH"/"$dirname"/"$fname" ]]
    do
      cnt=$(($cnt + 1))
      fname="$1.$cnt"
    done

    \mv "$1" "$GOMI_PATH"/"$dirname"/"$fname"
  else
    \mv "$1" "$GOMI_PATH"/"$dirname"
  fi
}

del_file() {
  # 10日以上経過したディレクトリを削除
  if [ "$(uname)" == 'Darwin' ]; then # Mac OSの場合、--dateオプションが使えない
    del_point_dirname="$(date -v-10d +%Y%m%d)"
  else
    del_point_dirname="$(date --date '10 day ago' +%Y%m%d)"
  fi
  for file in `\ls -1 "$GOMI_PATH"`; do
    if [[ $del_point_dirname > $file ]]; then
      \rm -rf "$GOMI_PATH"/"$file"
    fi
  done
}

ls_file() {
  # $GOMI_PATH内を表示
  \find "$GOMI_PATH" | fzf > selected
}

main() {
  if [ "$1" = "" ]; then # コマンドライン引数存在確認
    usage_exit
  else
    for file in "$@"; do
      move_file "$file"
    done
    del_file
  fi
}

check_opts "$@"
