#!/bin/bash

# USAGE: コマンドライン引数が空のとき実行
usage_exit() {
  echo "Usage: gomi FILENAME ..." 1>&2
  exit 1
}

move_file() {
  if [[ ! -e "$HOME"/gomi ]]; then # "$HOME"/gomiが存在しなければ作成
    \mkdir "$HOME"/gomi
  fi

   # ファイルを移動するディレクトリ作成
  dirname=$(date '+%Y%m%d')
  \mkdir -p "$HOME"/gomi/"$dirname"

  # ファイルを"$HOME"/gomi/$dirnameに移動
  if [[ -e "$HOME"/gomi/"$dirname"/"$1" ]]; then # 同名のファイルが存在した場合、filename.1に名称変更
    cnt=1
    fname="$1.$cnt"
    # filename.1が存在する場合、かぶりのない番号をつける
    while [[ -e "$HOME"/gomi/"$dirname"/"$fname" ]]
    do
      cnt=$(($cnt + 1))
      fname="$1.$cnt"
    done

    \mv -v "$1" "$HOME"/gomi/"$dirname"/"$fname"
  else
    \mv -v "$1" "$HOME"/gomi/"$dirname"
  fi
}

del_file() {
  # 10日以前のディレクトリを削除
  del_point_dirname="$(date --date '10 day ago' +%Y%m%d)"
  for file in `\ls -1 "$HOME"/gomi`; do
    if [[ $del_point_dirname > $file ]]; then
      \rm -rv "$HOME"/gomi/"$file"
    fi
  done
}

ls_file() {
  \find "$HOME"/gomi
}

main() {
  if [ "$1" = "" ]; then # コマンドライン引数存在確認
    usage_exit
  else
    for file in "$@"; do
      move_file "$file"
    done
    del_file
  fi
}

main "$@"
