#!/usr/bin/env ruby

# *.pyというファイルを*-0.pyに変える

if ARGV[0] == "-r"
  Dir.glob("*").map{ |fname| File.rename(fname, fname.gsub("-0.py", ".py")) }
else
  Dir.glob("*").map{ |fname| File.rename(fname, fname.gsub(".py", "-0.py")) }
end

