name: test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  chezmoi-apply:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install chezmoi
        run: |
          sh -c "$(curl -fsLS get.chezmoi.io)"
      - name: Dry-run apply dotfiles
        run: |
          chezmoi -S "$GITHUB_WORKSPACE/home" apply --dry-run --verbose
