name: test

on: [push] # pull_request のとき、ブランチ名が取得できずテストを通せない。

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: bash -c "$(curl -fsSL https://raw.githubusercontent.com/9sako6/dotfiles/${{ github.ref_name }}/install.sh)"
    - name: Run test
      run: deno test --allow-write --allow-read
      env:
        DENO_INSTALL: "${HOME}/.local"
        PATH: "${DENO_INSTALL}/bin:${PATH}"
